[Settings]
# 模拟器可达的本地 HTTP 服务
HTTP_URL_BASE=http://192.168.0.108:21000
GATEWAY_HOST=192.168.0.108
GATEWAY_PORT=4120
GATEWAY_IPV6=
GATEWAY_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp84jRqxS7KVFmhEydSsU
    STjON8GJXxXwVM68Zk4w4Hh08yhMhwVZJlXuMv9UQGpO4vDBn2PuiJWqPQXFP9Cg
    uRWE1fzEy+OcYw1nL0qiDlAayz0PGf5PvV8CFlP9Dvq/4Gw7GWvmpRDXLT53BTgd
    bZX2kYX2asbjwQg8YiF2XOsBe5dcdIVHaYxxk2+4cJlTZXWIjLON+ekkmYKlbu+4
    WdW+8J8+Q02xrxbMYrk6ZQgTcU3W3uDVvwd7+45ZIxyrPcPUgS6n0T2spvKrPAw+
    +xh5ScV9VpvNCrYRPrItVuUVNRp1/JyGHRHrBI+UWIhOLHfNcxr2sOACilTUlfDQ
    rQIDAQAB
    -----END PUBLIC KEY-----
GATEWAY_PUBLIC_KEY_FILE=../Sv/ServerData/gateway_public.pem

# MuMu x64 宿主 + ARM64 guest，双 Realm
CLIENT_ARCH=arm64-v8a
EMULATOR=true
USE_NEOX_SDK_BYPASS=true
