"""
ScanRpcName.py - 扫描客户端 Python 源码中的所有 RPC 方法名，并生成 C# 硬编码数组。
"""

import argparse
import os
import re
import shutil
import sys

# 默认内置与握手/底层系统 RPC 名称
SEED_RPC_NAMES = [
    # 握手与连接
    "seed_request",
    "seed_reply",
    "session_key",
    "session_key_ok",
    "connect_server",
    "connect_server_reply",
    "register_method",
    # 核心网关 RPC
    "login",
    "loginWithUrs",
    "heartbeatServer",
    "syncServerTime",
    "uploadDeviceInfo",
    "logCheckCheat",
    "uploadTouchHistory",
    "uploadLocation",
    "reliableRpcCall",
    "pullEvents",
    "syncAllIntelligenceRequest",
    "logout",
    # 实体下行 RPC
    "become_player",
    "on_heartbeat",
    "onSyncServerTime",
    "pullEventsReply",
    "reliableRpcAck",
    "syncAllIntelligence",
    "onLoginFail",
    # 实体类型名
    "ClientAccount",
    "ClientAvatar",
    "ClientBattle",
]

# 忽略扫描的目录（第三方库或无关资源）
EXCLUDE_DIRS = {
    "lib",
    ".git",
    "__pycache__",
    "shader_cache",
    "build",
    "dist",
}

CALL_PATTERN = re.compile(
    r'(?:callServerMethod|call_server_method|callServerMethodSeq|callServerMethodReliable)\w*\([\'"](\w+)[\'"]'
)
DEF_PATTERN = re.compile(r'^\s*def\s+(\w+)\s*\(')


def scan_rpc_names(scan_root: str) -> set:
    rpc_names = set(SEED_RPC_NAMES)
    scanned_files = 0

    if not os.path.isdir(scan_root):
        print(f"[Warn] 扫描目录不存在: {scan_root}", file=sys.stderr)
        return rpc_names

    for root, dirs, files in os.walk(scan_root):
        # 排除不需要扫描的目录
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]

        for file_name in files:
            if not file_name.endswith('.py'):
                continue

            file_path = os.path.join(root, file_name)
            scanned_files += 1

            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as fp:
                    expect_rpc_def = False
                    for line in fp:
                        # 匹配客户端发往服务端的 RPC 调用
                        for m in CALL_PATTERN.findall(line):
                            rpc_names.add(m)

                        # 匹配服务端推往客户端的 RPC 装饰器 (@rpc_method)
                        if '@rpc_method' in line:
                            expect_rpc_def = True
                            continue

                        if expect_rpc_def:
                            m = DEF_PATTERN.match(line)
                            if m:
                                rpc_names.add(m.group(1))
                                expect_rpc_def = False
                            elif not line.strip() or line.strip().startswith('#'):
                                continue
                            else:
                                expect_rpc_def = False
            except Exception as ex:
                print(f"[Error] 读取文件失败 {file_path}: {ex}", file=sys.stderr)

    print(f"[Info] 扫描完成: 共扫描 {scanned_files} 个 Python 文件，提取到 {len(rpc_names)} 个 RPC 方法名。")
    return rpc_names


def generate_csharp_code(rpc_names: list) -> str:
    lines = [
        "// <auto-generated>",
        "//     该文件由 ScanRpcName.py 自动生成，请勿手动修改。",
        f"//     生成 RPC 名称数：{len(rpc_names)}",
        "// </auto-generated>",
        "",
        "namespace Sv.Gateway.Protocol;",
        "",
        "public static class RpcNames",
        "{",
        "    public static readonly string[] All =",
        "    [",
    ]

    for name in rpc_names:
        lines.append(f'        "{name}",')

    lines.extend([
        "    ];",
        "}",
        "",
    ])

    return "\n".join(lines)


def main():
    default_input = r"D:\f7\Reverse\Script\py"
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_output = os.path.join(script_dir, "output", "RpcNames.cs")
    default_copy = r"D:\f7\Sv\Gateway\Protocol\RpcNames.cs"

    parser = argparse.ArgumentParser(description="扫描客户端源码并生成 C# RPC 方法名字典")
    parser.add_argument("--input", default=default_input, help=f"扫描根目录")
    parser.add_argument("--output", default=default_output, help=f"生成的 C# 文件路径")
    parser.add_argument("--copy-to", default=default_copy, help=f"自动同步目标路径")

    args = parser.parse_args()

    names_set = scan_rpc_names(args.input)
    sorted_names = sorted(names_set)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    cs_content = generate_csharp_code(sorted_names)

    with open(args.output, "w", encoding="utf-8", newline="\n") as fp:
        fp.write(cs_content)
    print(f"[Success] 已生成硬编码 C# 源码: {args.output}")

    if args.copy_to:
        copy_dest = os.path.abspath(args.copy_to)
        os.makedirs(os.path.dirname(copy_dest), exist_ok=True)
        shutil.copyfile(args.output, copy_dest)
        print(f"[Success] 已同步复制到: {copy_dest}")


if __name__ == "__main__":
    main()
